CFLAGS = -Wall -Wextra -g

callByReference: callByReference.c
	gcc ${CFLAGS} -o callByReference.out callByReference.c

const: const.c
	gcc ${CFLAGS} -o const.out const.c

clean:
#		del /f *.out *.o *‚.so
# Comment line above and uncomment line below for UNIX systems
	rm -f *.out *.o *.so