CFLAGS = -Wall -Wextra -g

primzahl: primzahl.c
	gcc ${CFLAGS} -o primzahl.out primzahl.c 

clean:
#		del /f *.out *.o *‚.so
# Comment line above and uncomment line below for UNIX systems
	rm -f *.out *.o *.so